//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psytest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public int GroupId { get; set; }
        public int CategoryId { get; set; }
        public int TestingId { get; set; }
        public string TestingSemester { get; set; }
        public int GenderId { get; set; }
        public int Age { get; set; }
        public int PointSum { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Testing Testing { get; set; }
    }
}
